"""
Herramientas generadas dinámicamente por el SkillForge Agent.
Este archivo es editado automáticamente por la IA para agregar nuevas capacidades permanentes.
"""

import os
import sys
import json
import requests
from typing import Any, Dict, List, Optional
from langchain_core.tools import tool
from agents.a2a_log import a2a_log

# -----------------------------------------------------------------------------
# [AUTOGENERATED TOOLS BELOW]
# -----------------------------------------------------------------------------



@tool
def get_weather_bogota():
    """
    Obtiene los datos meteorológicos actuales para Bogotá, Colombia en un formato simplificado.
    """
    import requests
    url = 'https://wttr.in/Bogota?format=3'
    response = requests.get(url)
    return response.text.strip()


@tool
def check_leap_year(year: int) -> str:
    """
    Verifica si un año es bisiesto.

    Args:
        year (int): El año a verificar.

    Returns:
        str: 'Es bisiesto' o 'No es bisiesto'
    """
    if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
        return 'Es bisiesto'
    else:
        return 'No es bisiesto'


@tool
def check_leap_year(year):
    """
    Verifica si un año es bisiesto.
    :param year: int
    :return: str
    """
    if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
        return 'Es bisiesto'
    else:
        return 'No es bisiesto'
